# Test configuration for eval_rm.py
# Use this for quick testing with limited samples and checkpoints

# Model directories to evaluate (just one for testing)
model_dirs:
  - "vlm_reward_model_balance_100_en_zh_total30k"

# Dataset path (same as used in training)
dataset_path: "/mnt/user-ssd/lilei35/trl/balance_100_en_zh_total30k"

# Base model path
base_model_path: "/mnt/user-ssd/lilei35/oss_models/Qwen2.5-VL-7B-Instruct"

# Only evaluate recent checkpoints for testing
checkpoint_pattern: "checkpoint-[23]*"

# Evaluation settings for testing
eval_batch_size: 2
max_eval_samples: 50  # Limited samples for quick testing

# Output file
output_file: "test_evaluation_results.csv"

# Model configuration
attn_implementation: "flash_attention_2"
min_pixels: 6272  # 8 * 28 * 28
max_pixels: 1605632  # 4096 * 28 * 28 